package.json
src/loadComponents.js
src/loadable.js
src/server/index.js

In order to not require regenerator/runtime.

refactor: remove async/await

---

README.md

change dynamic `import` syntax wrong link path

Fixed wrong link path

---

src/loadComponents.js
src/loadComponents.test.js

fix: fix loadComponents without valid state

---

.babelrc
.eslintignore
.gitignore
.npmignore
.prettierignore
.travis.yml
babel.js
example/package.json
example/yarn.lock
package.json
rollup.config.js
server.js
src/constants.js
src/utils/createSymbol.js
yarn.lock

Build is now done using Rollup.

feat: ship a single js file

---

src/loadable.js

fix: React 16.3 compatibility

---

package.json
src/__fixtures__/Dummy.js
src/loadable.js
src/loadable.test.js
yarn.lock

feat: attach static properties on load

---

packages/babel-plugin/src/__snapshots__/index.test.js.snap
packages/babel-plugin/src/index.test.js
packages/babel-plugin/src/properties/chunkName.js
packages/server/README.md
packages/webpack-plugin/src/index.js

fix(server): disable common chunks optim

---

packages/server/__fixtures__/stats.json
packages/server/src/ChunkExtractor.js

Source maps must no be included in links.
See #128

fix(server): ignore source maps

---

packages/component/src/library.js

fix: fix ref handler in `loadable.lib`

---

packages/server/src/util.js
packages/server/src/util.test.js

This is the fix for [missing feature in last PR](https://github.com/smooth-code/loadable-components/pull/155#issuecomment-440728651)

Support protocoll free public path in joinURLPath Method

---

packages/server/src/util.js
packages/server/src/util.test.js

fix(server): fix url join

---

packages/component/src/createLoadable.js

fix: ensure that component is mounted before calling `setState`

---

packages/server/src/util.js

fix(server): fix usage when compiled using webpack

---

website/src/pages/docs/suspense.mdx

I believe the documentation for Suspense can be improved by including the import of Suspense
Resolves #217

Improve documentation on <Suspense /> component

---

examples/server-side-rendering/src/client/App.js
examples/server-side-rendering/src/client/letters/E.js
packages/component/src/createLoadable.js
website/src/pages/docs/api-loadable-component.mdx
website/src/pages/docs/server-side-rendering.mdx

feat(server): add option to disable SSR

---

packages/server/src/util.js

fix(server): use `eval` to prevent webpack warning

---

.eslintrc.json
examples/suspense/package.json
examples/suspense/yarn.lock
packages/component/src/createLoadable.js

fix(suspense): fix suspense mode in React v16.8+

---

examples/razzle/package.json
examples/razzle/razzle.config.js
examples/razzle/src/client.js
examples/razzle/yarn.lock
packages/server/src/ChunkExtractor.js
packages/server/src/ChunkExtractor.test.js

Related: #235
```html
<link rel="preload" as="style" href="/static/css/Home.ab6fee9e.chunk.css">
<link rel="preload" as="script" href="/static/js/Home.29540c57.chunk.js">
<link rel="preload" as="script" href="/static/js/Logo.aa3dfd51.chunk.js">
<link rel="preload" as="script" href="/static/js/Welcome.b8e5d508.chunk.js">
<link rel="preload" as="script" href="/static/js/Intro.a96fcb22.chunk.js">
<link rel="preload" as="script" href="/static/js/runtime~client.0a907542.js">
<link rel="preload" as="style" href="/static/css/9.24bf1742.chunk.css">
<link rel="preload" as="script" href="/static/js/9.47319bf4.chunk.js">
<link rel="preload" as="style" href="/static/css/client.9823d995.chunk.css">
<link rel="preload" as="script" href="/static/js/client.3ed3a225.chunk.js">
<link rel="stylesheet" …
```

fix(server): fix loading order of assets

---

babel.config.js
packages/babel-plugin/package.json
packages/server/package.json
packages/webpack-plugin/package.json

This makes the output files smaller and it's easier to read.
Build passes.

build: add build target for Node

---

packages/babel-plugin/src/__snapshots__/index.test.js.snap
packages/babel-plugin/src/index.test.js
packages/babel-plugin/src/properties/chunkName.js

fix(babel-plugin): handle special chars in file names

---

package.json
packages/server/src/ChunkExtractor.js
packages/server/src/ChunkExtractor.test.js
website/src/pages/docs/api-loadable-server.mdx
yarn.lock

feat(server): authorize custom filesystem

---

website/_redirects
website/src/pages/docs/api-loadable-component.mdx
website/src/pages/docs/faq.mdx

docs: enhance docs

---

website/src/pages/docs/loadable-vs-react-lazy.mdx

docs(website): correct small typo

---

.eslintrc.json
babel.config.js
examples/client-side/package.json
examples/client-side/src/A.js
examples/client-side/src/B.js
examples/client-side/src/index.js
examples/client-side/yarn.lock
package.json
packages/component/src/createLoadable.js
packages/component/src/loadable.test.js
website/src/pages/docs/api-loadable-component.mdx
website/src/pages/docs/dynamic-import.mdx
yarn.lock

feat: support reactive dynamic loadable

---

examples/server-side-rendering/src/client/App.js
examples/server-side-rendering/src/client/Y/file.js
packages/babel-plugin/src/__snapshots__/index.test.js.snap
packages/babel-plugin/src/properties/chunkName.js

fix: fix chunkname mismatch

---

package.json
packages/component/.size-snapshot.json
packages/component/package.json
packages/component/rollup.config.js
packages/component/src/createLoadable.js
packages/component/src/loadable.test.js
yarn.lock

chore: optimize rollup config

---

package.json
packages/component/.size-snapshot.json
packages/component/rollup.config.js

fix: add @babel/preset-env in rollup config

---

website/src/pages/docs/api-loadable-component.mdx

Tiny fix of a bad url in doc
Click the link in the doc :)

docs: fix broken link

---

website/src/pages/docs/babel-plugin.mdx

Fix typo in babel-plugin doc page

---

package.json
packages/component/src/loadable.test.js
yarn.lock

chore: upgrade deps

---

examples/razzle/razzle.config.js

refer to https://github.com/smooth-code/loadable-components/issues/398

fix "Cannot find module 'fs'" problem

---

examples/razzle/package.json

I've struggled for a long time with the missing babel template, which needed to be loaded manually: 
https://github.com/smooth-code/loadable-components/issues/396
Adding the dev dependencies might help someone trying to get started using this example

Adding dev dependencies

---

packages/server/__fixtures__/letters-A.js
packages/server/__fixtures__/letters-B.js
packages/server/__fixtures__/letters-C.js
packages/server/__fixtures__/letters-D.js
packages/server/__fixtures__/letters-E.js
packages/server/src/ChunkExtractor.js

Fixes #230
Fixes the fact that in some cases the async chunks were not correctly reloaded on the server while correctly reloaded on the client.
Follow what was described in #230 
It works on my machine :tm:
On a separate repo though. I didn't test with the examples provided in this repo because I couldn't make them work even before my fix.
Have a nice day :wave: 
PS: Sorry about the many `push -f` :stuck_out_tongue:  Having a bad day with git!

fix: empty cache on chunks for each server reload

---

examples/client-side/README.md
examples/client-side/package.json
examples/client-side/src/index.js
examples/razzle/README.md
examples/suspense/README.md
examples/suspense/package.json
examples/suspense/src/index.js

This could solve issue #421
Add loadable packages to the next examples:
* client-side
* suspense
also I add instruction to README for each example.
Now, all the examples are more easy to run.
--

Add loadable packages to client-side and suspense examples

---

packages/server/src/util.js

this improves support with 'esm' package
Closes #455

fix(server): use require instead of module.require

---

website/src/pages/docs/api-loadable-webpack-plugin.mdx

I ran into the same issue as #225  and noticed that the outputAsset option is not documented on the website.
N/A

Document outputAsset in api-loadable-webpack-plugin.mdx

---

website/gatsby-config.js
website/package.json
website/yarn.lock

docs(website): use new google analytics

---

netlify.toml
website/package.json
website/yarn.lock

docs(website): remove unwanted button page in sitemap

---

website/src/pages/docs/code-splitting.mdx

fix small typo in code-splitting section, `chunck` -> `chunk`
confirmed docs looked correct

docs: fix typo, "chunck" -> "chunk"

---

packages/babel-plugin/package.json

Matches https://github.com/babel/babel-archive/blob/41686fb6022cd60c034592f3366cd1e46f3b4aeb/packages/babel-plugin-syntax-dynamic-import/package.json#L17-L19
Yarn v2 (berry) warns about this missing

fix(babel-plugin): add missing peer dependency

---

packages/webpack-plugin/package.json
packages/webpack-plugin/src/index.js

```
warning @loadable/webpack-plugin > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```
https://github.com/isaacs/node-mkdirp/blob/master/CHANGELOG.md
also

Use make-dir instead of mkdirp

---

website/src/pages/docs/code-splitting.mdx

Grammar + spelling.

---

website/src/pages/docs/faq.mdx

Let those considering loadable components know there is a Ruby on Rails solution in production.
n/a

Update faq.mdx with link to React on Rails Pro

---

.eslintrc.json
.prettierignore
CONTRIBUTING.md
babel.config.js
examples/server-side-rendering/src/client/letters/G.js
package.json
packages/component/.size-snapshot.json
packages/component/src/createLoadable.js
packages/component/src/loadable.test.js
packages/component/src/loadableReady.js

Changes made "post" #607 and #521

Release 5.14

---

packages/webpack-plugin/src/index.js

Related to https://github.com/gregberge/loadable-components/issues/636

fix: update hooks for webpack 5

---

packages/webpack-plugin/src/index.js

Fixes https://github.com/gregberge/loadable-components/issues/712

Fix Webpack 5 contenthash bug in LoadablePlugin

---

website/src/pages/docs/api-loadable-server.mdx

This changes the example in server docs to be compatible with Unix and Windows.
N/A

Make example OS agnostic

---

website/src/pages/docs/server-side-rendering.mdx

Fixed spell issue for documentation.

Fixed spell issue

---

packages/babel-plugin/src/__snapshots__/index.test.js.snap
packages/babel-plugin/src/index.js
packages/babel-plugin/src/index.test.js
packages/component/.size-snapshot.json
packages/server/__fixtures__/stats.json

Make lazy get handled by the babel plugin if imported
```shell
yarn test -t lazy
```

Added transformation of lazy in babel plugin

---

packages/server/src/ChunkExtractor.js
packages/server/src/util.js

Added getEntrypointPath to ChunkExtractor and reading json from fs

---

packages/component/.size-snapshot.json
packages/component/package.json
packages/server/.eslintrc.json
packages/server/.size-snapshot.json
packages/server/package.json
packages/server/rollup.config.js
packages/server/src/ChunkExtractor.js
packages/server/src/ChunkExtractor.test.js
packages/server/src/ChunkExtractorManager.js
packages/server/src/index.js
packages/server/src/util.test.js

Uses rollup / reuses component build approach

fix: correct esm configuration for loadable/server, fixes: #999
