gregberge/loadable-components

- src/server/index.js
When on the server doing:
`
getLoadableState(app).then(loadableState => { ... })
`
if no queries are found, throws an error because DeferredState is returned, not a Promise.
> Use Promise.resolve in the events no queries are found

- README.md
- src/index.js
Custom loadable components are not tracked by `componentsTracker`.
I just exposed `componentsTracker` so we can use it to track our custom components and give them an ID.
Also updated the doc :)
> Custom components doesn't works with SSR

- README.md
Hey guys! First of all, great library! It's the best React code splitting library I've used. I may have found something in the docs that needs a correction or clarification. I didn't see `<YourApp />` declared anywhere and using `app` works for me. If I've got that correct, here's a PR to help with make the change.
Thanks again for the great work!
> Change name passed in to renderToString

- README.md
I found README example mistake that `onHover` is ignored.
It's may be `onMouseOver`.
```
Warning: Unknown event handler property `onHover`. It will be ignored.
```
> Change onHover -> onMouseOver

- src/server/index.js
`your are` -> `you are`
Also specify that the configuration is missing in the Babel config.
> Fix typo and improve error message

- .eslintrc.json
- example/.babelrc
- example/.gitignore
- example/A/Component.js
- example/A/index.js
- example/App.js
- example/B/Component.js
- example/B/index.js
- example/package.json
- example/server.js
- example/yarn.lock
- src/componentTracker.js
- src/componentTracker.test.js
This issue fixes #59
It is possible to create a configuration which will result into a wrong state but it should not happen in 99.99% cases:
```
-App
-A
-B
-C
-D
-E
-F
-G
```
If BC and EFG have the same name we could have a problem because we rely on the order of loading of A and D and it could be different on client and server.
Anyway this edge case is acceptable, issue will solve 99% of use-cases.
> fix: fix module resolving

- src/loadComponents.js
- src/loadComponents.test.js
This swaps out an error with a rejected promise so that client UI doesn't break. Noticed when used in conjunction with [`@artsy/express-reloadable`](https://github.com/artsy/express-reloadable) that when reloads occur and module ids increment an error occurs when really there's no problem. 
(Really excellent lib -- was totally painless to setup compared to all of the others 👍)
> On client-side init error return rejected promise rather than throw

- README.md
That particular sample didn't include the Route import from `react-router`
> Add missing import to SSR part of the README.md

- server.d.ts
- types/index.d.ts
- types/test.tsx
- types/tsconfig.json
Hello, I'm trying to use this awesome package with Typescript on the server, and I've had some difficulties. 
When I `import {getLoadableState} from 'loadable-components/server'`, The Typescript compiler complains that it "Could not find a declaration file for module 'loadable-components/server'." I've managed to work around this by explicitly setting the path mapping in tsconfig.json to `"loadable-components/*": ["node_modules/loadable-components/types"]`, but I feel that's an unnecessary step for the end user.
This PR thus extracts the server-side type definitions to a separate `server.d.ts` to match the structure of the JS modules, which seems to be [the recommended way](https://github.com/Microsoft/TypeScript/issues/8305#issuecomment-214815674).
I've also added a type definition for …
> Fix server-side type definitions

- src/utils/resolveModuleDefault.js
- src/utils/resolveModuleDefault.test.js
To fix #103
HOC `loadable` can be used for any modules that webpack can import. I’ve tested it on [my project](https://github.com/sergeysolovev/site) and it works fine for both ES modules and modules containing markdown text.
> Support non-ES modules

- README.md
This PR updates some code examples in the readme.
The `pMinDelay`, `delay`, and `timeout` helpers all expect a promise as the first argument, but the examples show them receiving a function that returns a promise. This updates the examples so that the `loadable` function in each case receives the function argument instead of the helpers.
> fix: update readme examples

- .npmignore
#95 broke TS Definitions for `loadable-components/server`. That's because `server.d.ts` is not being exported on npm publish.
This fixes this #112
> Add server.d.ts to .npmignore

- README.md
I discovered that the `load()` function returns a Promise, so if you don't handle the error case, you get noise in the console. This isn't mentioned in the documentation, so I added a note about it.
> Add note about Promise returned by load

- packages/webpack-plugin/README.md
- packages/webpack-plugin/src/index.js
Adds option to emit file on build  [158](https://github.com/smooth-code/loadable-components/issues/158) by adding writeToDisk (default to false) to plugin options 
Test required app that runs 2 instances of webpack - client and server.  
Client webpack instance need to generate file that is later used by server instance. 
Razzle app maybe be a good candidate for that test
```
// add plugin instance in webpack for client config
plugins: [new LoadablePlugin()]
```
```
// 👇 generate absolute path to target file 
const filename = path.resolve(root, 'dist/loadable-stats.json'); 
// add plugin instance in webpack for client config
plugins: [new LoadablePlugin({filename:  writeToDisk: true})]
```
> add writeToDisk option to webpack plugin

- examples/razzle/src/server.js
The Razzle example loads the JSON as is instead of passing the path to ChunkExtractor via statsFile.
This will cause an error.
> Razzle example server statsFile fix

- packages/webpack-plugin/src/index.js
This is fix for [https://github.com/smooth-code/loadable-components/issues/168](https://github.com/smooth-code/loadable-components/issues/168).
> fix(webpack-plugin): fix TypeError when set writeToDisk true

- website/src/pages/docs/server-side-rendering.mdx
Found a typo in `Server Side Rendering` part of website.
Added missing `install` and `add` command in installation codes.
> fix install command in Server Side Rendering

- packages/server/README.md
- packages/server/__fixtures__/letters-A.css
- packages/server/__fixtures__/main.css
- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
Hi. We have a requirement to render our css inline in certain situations, and so I had a crack at implementing it with the loadable library. Please do let me know what you think about the approach.
In order to improve page speed score, or to render AMP SSR pages alongside the main app, it can be a requirement to render css inline.
This has been added as an option to the existing `chunkExtractor.getStyleTags()` and `chunkExtractor.getStyleElements()` functions via an `inline` boolean parameter. 
Additionally a `chunkExtractor.getCssString()` function has been added to allow developers further control over how to render css (an example use requirement being passing the css string to a style tag using AMP's `amp-custom` attribute)
Appropriate tests have been added to `ChunkExtractor.test.js`
> Inline CSS options

- examples/razzle/razzle.config.js
- packages/server/src/util.js
- packages/webpack-plugin/README.md
- packages/webpack-plugin/src/index.js
- website/src/pages/docs/api-loadable-webpack-plugin.mdx
This is my stab at https://github.com/smooth-code/loadable-components/issues/179 .
I've added `path` option to the webpack plugin, that allows specifying where loadable-stats are written to when `writeToDisk` option is set to true. This way webpack assets compiler always use `filename` and not absolute path when adding loadable stats to the assets. If `path` is not set by default loadable-stats are written to `output.path` set in webpack config.
I also fixed issue I had with `eval('module.require')` trick as it was throwing errors (eval is not a function). I've replaced it with `__non_webpack_require__` and that seems to be working fine.
I've tested it with razzle example in the repo and it works fine both in dev and production mode (after yarn build command).
Closes …
> fix issue with @loadable/webpack-plugin not working in production mode and SSR

- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
When you using loadable components server side
I want to be able to provide extra attributes to generated script tags, especially a `nonce` attribute used for `Content-Security-Policy`.
I added a small test on how you can use this new extraProps.
> Allow to specify extra attribute in getScriptTags

- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
Add extra prop options for `getLinkTags` and `getLinkElements`.
The latest version added extra prop options for all the get tag functions. It seems as though links were missed in this even though they were documented as having the option.
Added snapshot tests for the new options. 
Note: I ran prettier over the project but it seemed to change some extra lines. Not sure if it was upto date previously.
> fix: Add extra props option for links

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/properties/chunkName.js
bundle-safe template literal chunks
Webpack sanitizes the chunk names replacing several characters with *"-"* character.
https://github.com/webpack/webpack/blob/master/lib/Template.js#L97
The variable part of the template literal has to be sanitized at runtime in the same way to match with the generated chunk id,
```js
const X = loadable(props => import(`./letters/${props.letter}`))
<X letter="A.secondary" /> // generated bundle is letters-A-secondary-bundle-8f2acafd.js
```
loadable-stats.json chunks
```
{
"assetsByChunkName": {
"vendors~letters-A-secondary~letters-B~moment": "vendors~letters-A-secondary~letters-B~moment-bundle-bf611092.js",
"letters-A-secondary": [
"letters-A-secondary.css",
"letters-A-secondary-bundle-7b3653b1.js"
],
"letters-B": "letters-B-bundle-32c679b2.js", …
```
> Fix agressive code splitting when passing props containing "." 

- packages/server/__fixtures__/stats.json
- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
We use query params for cache-busting (eg, `chunkFilename: '[name].js?[chunkhash]'`), but `extname()` can't properly get the extension when there's a param attached. This change would allow the use of query params.
> Allow query-param cache busting in chunk names

- website/src/pages/docs/prefetching.mdx
I think the docs are incorrect, the extra arrow function is not necessary and it's missing `import`.
> Update docs to correct syntax for prefetching example

- website/src/pages/docs/babel-plugin.mdx
It took me an hour+ to figure out why I wasn't getting chunk names in my stats file... turns out babel was stripping the comments injected by this plugin. It isn't immediately obvious how the plugin works, so I figured I'd save the next person some time and make a note here.
Nothing; it's just a documentation change.
> Warn against having comments=false in babel

- website/src/pages/docs/code-splitting.mdx
- Fix minor typo in code-splitting documentation on website
N/A
> fix(docs): fix minor typo in documentation for code-splitting

- examples/server-side-rendering/webpack.config.babel.js
- packages/component/src/loadableReady.js
- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
See https://mathiasbynens.be/notes/json-dom-csp
Dynamic loading works in `examples/server-side-rendering` and `examples/razle`.
> Use inline JSON to enabling CSP without `unsafe-inline`

- website/src/pages/docs/loadable-vs-react-lazy.mdx
The link to the SSR page from the [Comparison with React.lazy](https://www.smooth-code.com/open-source/loadable-components/docs/loadable-vs-react-lazy/) page is broken as it's missing a trailing slash and ends up taking users to the 404 page. 
* [Broken URL](https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering)
* [Fixed URL](https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/)
> docs: fix broken link

- website/src/pages/docs/getting-started.mdx
After migrating from `loadable-components` package I have noticed that even I'm not using SSR but `@loadable/babel-plugin` (`loadable-components/babel` earlier) is required in my setup. 
This change extends Installation note by exposing that `babel-plugin` is also needed when you use chunks.
> docs: add note that `@loadable/babel-plugin` is not only needed in SSR

- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
- website/src/pages/docs/api-loadable-server.mdx
Allow the attributes arguments to be a function to possibly map the chunks to attributes.
Currently it uses the same argument but checks if it is a function or an object.
Also the attribute function could get `null` as an argument in case the `__LOADABLE_REQUIRED_CHUNKS__` tag
Looking forward to your feedback.
tests included
> implement attribute function

- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
- website/src/pages/docs/server-side-rendering.mdx
Add support for passing `publicPath` to `ChunkExtractor`. This will allow consumers to override `publicPath` at runtime.
Currently in our usage we are loading the stats file, manually overriding the `publicPath`, and then injecting that stats object into `ChunkExtractor`. This seems like a simple enough change that it warrants being supported out-of-the-box.
Formatted docs section: https://deploy-preview-292--loadable.netlify.com/docs/server-side-rendering/#override-statspublicpath-at-runtime
closes https://github.com/smooth-code/loadable-components/issues/269
Added new test cases to `packages/server/src/ChunkExtractor.test.js`.
> feat(ChunkExtractor): support publicPath override

- packages/server/src/ChunkExtractor.js
Serverless is becoming popular and bundle size is important. This PR avoids importing the whole lodash code, even in the server.
Tests pass for `ChunkExtractor.js`, the only affected file.
> Improve lodash imports to reduce size of serverless bundles

- website/src/pages/docs/code-splitting.mdx
The current use of `speed` and `reduce` on the code-splitting page of the documentation is incorrect. To be grammatically correct, I've added an `s`. 
No tests needed as it is just a grammar update to the documentation 😃
> add s to speed and reduce so copy is gramatically correct

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/properties/resolve.js
Node modules were incorrectly getting resolved to relative path during server side rendering.
Reference - [Issue #301](https://github.com/smooth-code/loadable-components/issues/301)
If your import statement is
`const ComponentName = loadable(() => import("some_npm_module") );`
in a file located at -
`~/my-project/src/client/components/my-component.js`
Node was resolving the import path to this relative path :-
`~/my-project/src/client/components/some_npm_module.js`
But this PR will fix this behavior to resolve to its correct path :-
`~/my-project/node_modules/some_npm_module.js`
> fix(babel-plugin): Use require.resolve instead of relative path resolution

- packages/component/src/loadableReady.js
- packages/component/src/sharedInternals.js
- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
- packages/server/src/sharedInternals.js
- website/src/pages/docs/api-loadable-component.mdx
- website/src/pages/docs/api-loadable-server.mdx
Fixes #311 
Loadable components currently doesn't support having multiple react apps on the same page. This is because it uses the hardcoded id of `__LOADABLE_REQUIRED_CHUNKS__`  in a script tag to check if a chunk has loaded. This PR aims to add the feature to add a namespace to each app to make this possible. 
Added test cases on the server side to make sure that the namespace was being added to the `script` id. 
On the client side, verified manually if loading 2 different react apps triggers 2 different `loadable` events
> Multiple React applications on same page support

- packages/component/src/createLoadable.js
- website/src/pages/docs/api-loadable-component.mdx
> feat: add `load` method that returns a Promise

- packages/server/src/util.js
- Regex can be [heavy handed](https://ebaytech.berlin/slow-regexp-dying-node-js-7a862ed6ea65).
```sh
yarn test packages/server/src/util.test.js
yarn run v1.16.0
$ jest packages/server/src/util.test.js
PASS  packages/server/src/util.test.js
util
#joinURLPath
✓ should join paths with relative public path (2ms)
✓ should join paths starting with "/" (1ms)
✓ should join paths with absolute public path
✓ should join paths with protocol free public path
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        0.869s, estimated 1s
Ran all test suites matching /packages\/server\/src\/util.test.js/i.
✨  Done in 2.02s.
```
> use more performant url join impl

- examples/razzle/package.json
The Razzle example is missing @loadable/component and @loadable/server in package.json to run.
With this commit, running the following commands should not fail anymore:
```
cd examples/razzle
npm install
npm run build # or start
```
> Add required dependencies to run the razzle example

- packages/component/src/loadableReady.js
I didn't check this, but it seems trivial
fixes #397
> support ie11

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/index.test.js
- packages/babel-plugin/src/properties/resolve.js
Currently, the Babel plugin successfully transpiles template literals, but doesn't work when building a string using `+`. i.e. this works:
```js
import(`my-lib/${componentId}`)
```
But this does not:
```js
import('my-lib/' + componentId)
```
The latter fails with an error:
> TypeError: Property value expected type of string but got null
This PR fixes this issue by checking to see if the import expression is a BinaryExpression. I'm not sure if there are any other types of expressions that should be checked for, but this solves the issue for BinaryExpressions at least.
I added a new test to verify that it works and also tested it in a real app.
> Babel plugin: Fixed bug when using + concatenation instead of a template literal

- packages/server/src/ChunkExtractor.js
- packages/webpack-plugin/src/index.js
Potential fix for feature request in issue #344 which will add SRI integrity to be html tags before sending to client, if the value exists on the asset.
```js
const SriPlugin = require('webpack-subresource-integrity');
const LoadablePlugin = require('@loadable/webpack-plugin');
module.exports = ({
...
plugins: [
...
new SriPlugin({
hashFuncNames: ['sha256', 'sha384'],
}),
new LoadablePlugin(),
],
});
```
Also worth adding the `crossorigin` key (this functionality already existed and isn't being introduced by this PR)
```js
chunkExtractor.getScriptTags({ crossorigin: 'anonymous' })
```
Confirm that during SSR run the tags have `integrity` key with correct value
```html
<script
async
data-chunk="HelloWorld"
src="/1.bundle.js"
crossorigin="anonymous" …
```
> Accept additional attributes for assets to support SRI

- website/src/pages/docs/prefetching.mdx
Small update to the example in the documentation listing `webpackPrefetch` when `webpackPreload` is intended as far as I can tell.
N/A
> [doc] use webpackPreload hint in example

- examples/server-side-rendering/babel.config.js
- examples/server-side-rendering/src/server/main.js
- packages/babel-plugin/src/index.js
- packages/babel-plugin/src/properties/requireAsync.js
- packages/babel-plugin/src/properties/state.js
- packages/component/.size-snapshot.json
- packages/component/src/resolvers.js
- packages/server/src/ChunkExtractor.js
Using [standard babel hack](https://jamie.build/babel-plugin-ordering.html) to "hoists" own plugin transformation over any other.
Hopefully should fix #466
> fix: apply loadable transformations before any other

- packages/webpack-plugin/src/index.js
- website/src/pages/docs/server-side-rendering.mdx
Webpack `stats.toJson` is an expensive operation for large builds, and the loadable-components webpack plugin runs it each emit (so it slows down the watching recompile). Often there are many reasons besides loadable-components to have a stats asset in a build, and large speed savings can be made by combining them into one.
This change avoids running `stats.toJson` (or adding the emit hook at all) if both `outputAsset` and `writeToDisk` are false, in which case the returned value is unused.
> perf: avoid calling stats.toJson if possible

- examples/server-side-rendering/src/client/App.js
- examples/server-side-rendering/src/client/letters/G.js
- packages/component/src/createLoadable.js
Fixes #345. See description there for more details. 
**tl;dr**: in cases where `ssr: false` is set, this PR fixes the way we render the component on the client to match what the server is doing, avoiding problematic SSR hydration mismatches (https://reactjs.org/docs/react-dom.html#hydrate).
Updated the SSR example to add a new letter, `G`, which is rendered on the page with both `ssr: true` and `ssr: false`. Without the change applied, the DOM looks like this (incorrect):
with the change applied, the DOM now correctly looks like this:
As mentioned in #345, I can't see any existing integration tests for SSR: if I missed some or if you think it's worth adding some, I'm happy to help set that up. Thanks in advance for reviewing!
> Avoid synchronous loading on client if options.ssr is false

- website/src/pages/docs/api-loadable-server.mdx
The `ChunkExtractor.outputPath` option is also used by functions like `getCssString`, not only `requireEntrypoint`, so I adjusted that.
> docs: fix ChunkExtractor.outputPath comment

- packages/server/src/ChunkExtractor.js
- yarn.lock
When getting the preload assets, sort them so that the style assets are first.
I saw a PR over in next.js (https://github.com/vercel/next.js/pull/9486). Apparently preloading the JS first can slow down some browsers and delay the styles loading and therefore negatively impact performance/lighthouse scores.
I tested the approach on our own site and it led to quite a dramatic improvement in lighthouse score.
I tried to run the tests locally but it errored with something I didn't understand. I'm afraid I don't have the time at the moment to wrap my head around it but figured this PR may be useful to some people so would submit it anyway.
> Sort preload assets so that styles are first

- packages/server/src/util.js
`smartRequire` is cleaning the cache before requiring module, and that might keep reference to an older version, causing a memory leak.
- remove module from the cache
- (added) remove module from parent.children
- (added) remove module from children.parent
The algorithm is borrowed from [rewiremock](https://github.com/theKashey/rewiremock/blob/master/src/wipeCache.js#L34)
> fix: memory leak in module cache management, fixes #560

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/index.test.js
- packages/babel-plugin/src/properties/chunkName.js
fix custom webpackChunkName for aggressive import
`babel-plugin` will ignore the correct custom `webpackChunkName` during dynamic import.  I think it makes sense to keep this, it can store chunks in the specified directory.
> fix custom webpackChunkName for aggressive import

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/properties/isReady.js
- packages/component/.size-snapshot.json
- packages/component/src/createLoadable.js
- packages/component/src/loadableReady.js
- packages/component/src/shared.js
- yarn.lock
Only SSR-ed chunks could be tested for `isReady` via webpack cache. Others should go through `requireAsync` and track their process in a internal state variables.
> Allow webpack cache isReady only for initial chunks

- package.json
- packages/component/package.json
- packages/component/src/createLoadable.js
- packages/component/src/loadable.js
- packages/component/src/loadable.test.js
- packages/component/src/resolvers.js
- website/src/pages/docs/api-loadable-component.mdx
- yarn.lock
See https://github.com/gregberge/loadable-components/issues/245
Currently to create a loadable component, the module that is asynchronously loaded must export the component as the default export (or be a commonjs module exporting the component as `module.exports`). This is problematic/limiting because:
- There are good reasons to avoid default exports (prevents grepping a codebase to find usages of an export, prevents import auto completion from working in most/all IDEs)
- It is not possible to make [multiple loadable components using the same split point](https://github.com/gregberge/loadable-components/issues/245#issuecomment-564467163) (instead one must hard code chunk names with webpack "magic comments" - not a standard feature)
See …
> Add support for named exports

- packages/server/src/ChunkExtractor.js
fix #628
fix a `key` warning when rendering  page.
> fix: add key to chunks script elements

- packages/component/.size-snapshot.json
- packages/server/src/ChunkExtractor.js
- packages/webpack-plugin/src/index.js
- yarn.lock
make packages compatible with Webpack 4 and Webpack 5
> feat: make packages webpack 5 compatible

- packages/component/src/createLoadable.js
For components, which are static, there is no reason to derive cache key from props.
👉 Do not derive cache key if component is static, fixes #629
> fix: do not derive cache key if component is static

- .travis.yml
In order to maintain better integrity:
-  run `build` for selected examples during CI
This shall ensure that webpack integration is working correctly, as well as TypeScript integration (for selected use cases)
> chore(tests): build examples during CI

- examples/webpack/webpack4/package.json
- examples/webpack/webpack4/src/client/App.js
- examples/webpack/webpack4/src/client/letters/B.js
- examples/webpack/webpack4/src/client/letters/C.js
- examples/webpack/webpack4/src/server/main.js
- examples/webpack/webpack5/package.json
- packages/component/.size-snapshot.json
- packages/component/src/loadableReady.js
`loadableReady` might resolve when `webpack` is still running modules _stored_ `__LOADABLE_LOADED_CHUNKS__` which will cause too early execution.
Solution: postpone `loadableReady` to _one promise later_.
> Fix sync resolution

- packages/server/src/ChunkExtractor.js
`requireEntrypoint` failed when main asset's path has query.
> fix: remove main asset path query

- packages/server/src/ChunkExtractor.js
- packages/webpack-plugin/src/index.js
Ignore single css chunk when `RequiredChunks` added into HTML output during SSR. 
Issue: https://github.com/gregberge/loadable-components/issues/688
> fix: ignore single css chunk (close #688)

- examples/server-side-rendering/README.md
The SSR example doesn't work without building the library, add that as a step for running the example.
The SSR example doesn't work without building the library, add that as a step for running the example. Per issue: https://github.com/gregberge/loadable-components/issues/693
Not needed
> Include build library step in SSR Example README

- packages/component/src/createLoadable.js
Fixes #727
Adding `displayName`s to the generated loadable components makes them identifiable in react devtools.
Acceptance testing: Load one of the examples in a browser with react-devtools, make sure that the loadable wrappers dont just say "Anonymous"
Unit testing: just make sure that `displayName` is set on generated components.
> fix: add displayNames to generated components

- packages/component/.size-snapshot.json
- packages/component/src/loadableReady.js
- packages/webpack-plugin/src/index.js
- website/src/pages/docs/api-loadable-component.mdx
- website/src/pages/docs/api-loadable-webpack-plugin.mdx
Addresses: https://github.com/gregberge/loadable-components/issues/635
We have a case where we're running multiple Webpack runtimes on the same page which both use Loadable. This change adds an optional `chunkLoadingGlobal` option to `LoadablePlugin` and `loadableReady` which namespaces `jsonpFunction` or `chunkLoadingGlobal`.
I didn't see unit tests for `LoadablePlugin` but I tested in a local application which rendered two Webpack apps in the same page. I can push this to a repo if you'd like. It correctly adds the namespace:
`namespace: 'header'`
```
(window["__header__LOADABLE_LOADED_CHUNKS__"] = window["__header__LOADABLE_LOADED_CHUNKS__"] || []).push([["foo"],{
```
`namespace: 'content'`
```
(window["__content__LOADABLE_LOADED_CHUNKS__"] = …
```
> feat: support multiple Webpack runtimes

- packages/webpack-plugin/src/index.js
I noticed while upgrading a codebase from webpack v4 -> v5 that there seemed to be a significant increase in incremental build times. 
From a local profile, the time seemed to be spent on a `stats.toJson` call originating from the loadable webpack plugin
Updating the `toJson` call so that it specifies [all: false](https://webpack.js.org/configuration/stats/#statsall) improves the time spent on this call from 40seconds -> 55ms (for the specific codebase i tested on)
I checked this change against webpack 4 on our codebase and it also reduced the time spent from ~9s -> 500ms
I tested this change locally against both a webpack 4 build and webpack 5 build and loadable worked as expected in both cases.
> [perf] Set all:false in stats.toJson call

- website/src/pages/docs/code-splitting.mdx
`import()` syntax is officially a part of ES2020 so this note can be refined.
https://github.com/tc39/proposal-dynamic-import
n/a
> fix docs: import() syntax a part of language

- packages/server/src/util.js
clearModuleCache is causing memory leaks in staging. Added optional env var to prevent it.
> Prevent memory leaks in staging by adding env var

- packages/webpack-plugin/src/index.js
I'm currently working on a pretty massive project with hundreds of split points, thousands of modules (plus node_modules), CSS, hot reloading, all the goodies... but *LoadablePlugin* was taking a very significant amount of time to run (about 1.2s). With these changes it went down to ~7ms.
> feat: webpack plugin doesn't need all chunk info (150x faster)

- packages/webpack-plugin/src/index.js
Fixes #770 by setting `cachedAssets: true`.
Run a webpack build using the plugin. Cached assets are found in the generated stats JSON file.
> fix: add cachedAssets to stats options

- CONTRIBUTING.md
- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
- packages/webpack-plugin/src/index.js
this pull request solves the problem of integrity not being added to script tags when using [`webpack-subresource-integrity`](https://github.com/waysact/webpack-subresource-integrity). it seems that either https://github.com/gregberge/loadable-components/pull/436 did not include everything necessary or possibly my configuration is different but i was unable to get things working properly without these changes. other users are seeing this issue as well as seen in https://github.com/gregberge/loadable-components/issues/563
- add [`webpack-subresource-integrity`](https://github.com/waysact/webpack-subresource-integrity) to your webpack plugins
- you should now see the `integrity` attribute in `loadable-stats.json` and on your `script` tags when using `ChunkExtractor.getScriptTags`
> fix: subresource integrity

- website/src/pages/docs/api-loadable-server.mdx
These docs disagree with their implementation. The docs mention `link` tags but the implementation uses `style` tags. The implementation seems obviously correct so I assume it's the docs that need fixing.
Here is `getInlineStyleTags` using `style` tags as expected:
https://github.com/gregberge/loadable-components/blob/629c80e42eea605a32dafd7b52faf3140e1aab28/packages/server/src/ChunkExtractor.test.js#L463-L479
Here is `getInlineStyleElements` using `style` tags as expected:
https://github.com/gregberge/loadable-components/blob/629c80e42eea605a32dafd7b52faf3140e1aab28/packages/server/src/ChunkExtractor.test.js#L622-L650
N/A
> Fix getInlineStyleTags/Elements docs.

- packages/server/src/util.js
Using `module.hot` is forcing me to use Webpack `HotModuleReplacementPlugin` and excluding `@loadable/server` from `nodeExternal()` so that `module.hot` is present. (8f10896058cdfd542c2aca1a982c2e14b1d9707a)
Then `__non_webpack_require__` is used in `smartRequire` (https://github.com/gregberge/loadable-components/blob/main/packages/server/src/util.js#L30) but `clearModuleCache` is clearing cache from `require` not from `__non_webpack_require__`.
This PR should fix this problem.
See #821
> fix: Clear correct cache when compiling with Webpack

- packages/component/src/createLoadable.js
I think loadAsync should like loadSync resolve module and copy Component statics (hoistNonReactStatics).
In some cases, I hope loadable can trigger load end, so add onLoad in options.
> fix: loadAsync resolve

- packages/component/src/createLoadable.js
I guess the cache in `preload` and `load` methods is not used on purpose but I was curious whether you'd be interested in this change, maybe under an option or a different static method `cache`.
The use case for me is that I did try to prefetch pages on link hover, but after transiting to the prefetched page I saw a blink of white page in between the route transitions, even though I was blocking the transition until the module was fetched.
This only happened on the first transition, subsequent transitions to the cached pages didn't have the blink anymore, which lead me to this change.
> Cache promise on load/preload

- packages/component/src/createLoadable.js
- packages/component/src/loadable.test.js
corrections on top of https://github.com/gregberge/loadable-components/pull/830
> fix: use stable promises for load/preload/React

- website/src/pages/docs/server-side-rendering.mdx
The docs on server-side rendering could be interpreted incorrectly and one can miss the important fact that the order of calls to `ChunkExtractor` matters alot. Specifically that you have to render the app _before_ collecting script tags.
This adds a note that explicitly states the importance of the call order. I personally spent way too many hours debugging why my app was not hydrating properly, and without any errors or docs on this matter, it's quite easy to miss this important fact.
There are also a number of issues where the cause is this exact configuration issue. Hopefully this will help alleviate any similar mistakes in the future.
>  Add note on order of calls when server-side rendering

- website/README.md
- The old `gatsbyjs.org` link is resolved as relative by GitHub and raise a 404 when clicking
- Gatsby have changed their domain to `gatsbyjs.com`
[gatsbyjs](https://gatsbyjs.com/)
> chore: fix gatsbyjs link in website/README.md

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/index.js
- packages/babel-plugin/src/index.test.js
Allow renaming imports
Added and updated snapshots, checked that only imports were added
> Support renamed imports in babel-plugin

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/index.js
- packages/babel-plugin/src/index.test.js
I would like to wrap `loadable` in my own higher order component functions.  Loadable by default only injects a webpack chunk name  for `loadable` and `lazy`, but can readily accept additional identifiers.
This PR allows us to rewrite
```
// Loadable
const LoadableHelpPage = loadable(() => import('./HelpPage'), {
resolveComponent: components => components.HelpPage,
})
// Our custom HOC
const HelpPage = PageHOC(LoadableHelpPage, {...additional page props })
```
to
```
const HelpPage = LoadablePageHOC(() => import('./HelpPage'), 'HelpPage', { ...additional page props })
```
We actually have a separate HOC for modals, so we would not be able to simply rename LoadablePageHOC to loadable for the sake of the existing babel plugin.  With the changes, we can specify `additionalIdentifiers: [ …
> Allow additional identifiers to be passed in to the babel plugin

- packages/babel-plugin/src/__snapshots__/index.test.js.snap
- packages/babel-plugin/src/index.js
- packages/babel-plugin/src/index.test.js
- packages/server/src/ChunkExtractor.test.js
The old behaviour was allowing `loadable` to be of any source, even a local variable. Signatures tightened this logic and broke some user code.
Fix: default to `loadable` name unless signatures are overridden.
> fix: correct babel plugin default signature to allow any source of 'loadable'

- packages/component/.size-snapshot.json
- packages/component/package.json
- packages/server/__fixtures__/stats.json
Vite 5.0.0+ now removes the `exoports.default` to `default` ESM export proxy it used previously.<br />
Unfortunately this breaks the following import `import loadable from '@loadable/component'` because the dependency is treated as CommonJS export and `vite` doesn't proxy the `default` export for CommonJS files anymore.<br />
There is still a flag to enable the old behaviour, but that flag is due to be removed in Vite 6.0.0+, which would break the default import with this extension<br />
This is a quick and dirty fix duplicates the default export as a named export called `loadable`, so we can also import `import { loadable } from '@loadable/component'` which works with Vite 5.0.0+.<br />
More info about the deprecation: https://vitejs.dev/guide/migration#ssr-externalized-modules-value-now- …
> fix: add "exports" field to package.json and rename ESM bundle to .mjs to fix ESM imports on node.js

- packages/component/src/createLoadable.js
- packages/component/src/loadable.test.js
I've failed to understand root cause behind #990 and a _proper way_ to resolve the problem.
As "let's do something" correction I am removing the offending piece of code (typescript should handle that) and that should give more time to find the real fix.
> fix: correct react-is for mjs export

- .eslintrc.json
- packages/server/src/ChunkExtractor.js
- packages/server/src/ChunkExtractor.test.js
- packages/server/src/ChunkExtractorManager.js
- packages/server/src/index.js
- packages/server/src/util.test.js
Brings back extensions removed in 114cea2b61ef644d3b794a9b5f48df69f0f5400b, which caused issue #1005.
Warning! The infra (particularly Webpack 4) did not let me even install the repository, so this is a "blind fix".
Testing should be fairly simple though if someone is able to:
- Build the package
- Open ESM file from dist directory using node (e.g. `node ./dist/esm/loadable-server.esm.mjs`)
- Observe if it doesn't crash upon module resolution
> Bring back extensions in server package

- packages/component/package.json
- packages/server/package.json
- yarn.lock
Resolves #1014.
Appends `^19.0.0` to the `react` peer dependencies in both the `@loadable/component` and `@loadable/server` packages. I don't think there's anything about those package's usage of `react` that would prevent React 19 from being compatible with them.
I struggled for a long time trying to get node v12 installed (via [mise](https://mise.jdx.dev/)) as well as installing deps with `yarn`. Having to install Python 2.x is a pain.
Additionally, I had to replace a reference to what appears to be a private atlassian registry in the lockfile with a reference to the `yarnpkg` registry.
After a while I gave up on node 12 and ran tests with node 16 (node 18 didn't work either) after manually executing parts of the `prepare` script. All tests passed on my machine, though the repo is still …
> Update `react` peer dependency ranges to include v19 
